### ISSUE TITLE
Ошибка импорта ENUM

### ISSUE THREAD

**Issue by WhidRubeld** [somersets/react-native-rustore-iap#16]
Пример ENUM, импорт которого вызовет ошибку. Предлагаю все ENUM вынести в общий импорт

`import { RuStorePurchaseState } from '@devsomersets/react-native-rustore-iap/lib/typescript/enums'`

**Comment by somersets** [comment]
Путь импорта неправильный

пн, 24 июл. 2023 г. в 15:45, Vasilev Gennady ***@***.***>:
