### ISSUE TITLE
Интеграция в Expo

### ISSUE THREAD

**Issue by WhidRubeld** [somersets/react-native-rustore-iap#8]
Приветствую. Планируете ли сделать интеграцию для Managed проектов Expo с использованием expo-config-plugin?

**Comment by somersets** [comment]
@WhidRubeld Здравствуйте, с Expo особо не работал и в общем то не планировал
Если бы вы указали ссылку на какой-нибудь мануал или доку по интеграции я бы взглянул на выходных

**Comment by WhidRubeld** [comment]
https://docs.expo.dev/guides/config-plugins/

Данная небольшая интеграция позволит исключить работу с android / iOS папками для Managed проектов через сборку Internal билдов с помощью EAS утилиты.

Для проектов Expo потребуется expo-dev-client (https://docs.expo.dev/development/create-development-builds/). Тем самым можно будет создать клон приложения Expo Go, где будет интегрирована ваша библиотека для тестирования и реализации требуемых экранов.

https://docs.expo.dev/guides/config-plugins/#modifying-the-androidmanifestxml
Вот более наглядный пример, где требуется вписывать в AndroidManifest определенные ключи.

Вот пример файла для библиотеки react-native-voice
https://github.com/react-native-voice/voice/blob/master/plugin/src/withVoice.ts

Думаю у вас не возникнет затруднений в данной интеграции. По сути вам нужно лишь добавить запись в gradle через `mods.android.gradleProperties`(https://docs.expo.dev/guides/config-plugins/#default-mods).

Проверять по сути нужно в проекте, который был создан через expo-cli. Тестирование можно проводить через сборку npm pack с последующей установкой локальной зависимости (gz архив прямо внутри проекта), где в package.json указывается link до проекта.

**Comment by WhidRubeld** [comment]
Если возникнут затруднения, то думаю я смогу выделить время, чтобы вам помочь написать данное нововведение в ближайшие дни.

**Comment by somersets** [comment]
@WhidRubeld Подскажи пожалуйста, как мне проверить что все сделано правильно?

**Comment by WhidRubeld** [comment]
1. Собрать локальный пакет и включить его в package.json чистого проекта expo-cli
2. Для проекта вписать следующий конфигурацию в eas.json в конфигурацию билда, допустим, в `development`

```
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "dev"
    },
```
3. Выполнить `eas build -p android --profile development` чтобы получить APK
4. Запустить APK, запустить Expo проект и подключиться к разработка через него, чтобы вызвать какой-нибудь метод из библиотеки

Успех выполнения 3 и 4 пунктов будет означать, чтобы все сделал правильно

**Comment by WhidRubeld** [comment]
Если будут проблемы в сборке пакета, то 3 пункт выбросит ошибку с трассировкой кода сборки Android

**Comment by somersets** [comment]
@WhidRubeld В общем вроде бы разобрался и сделал все что нужно, в readme добавил пункт для expo.
Пункт 3, 4 прошел успешно. Методы вызываются, но там ошибка приходит с рустора, т.к в рустор не выкладывал аппу, а так если все условия соблюдены до будет по идее все ок.

**Comment by WhidRubeld** [comment]
Отлично, спасибо!
